# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=64)),
                ('card_description', models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.List'),
        ),
    ]
