# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=64)),
                ('comment_content', models.CharField(max_length=124)),
                ('comment_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Card')),
            ],
        ),
    ]
