# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_comment_comment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_title',
        ),
    ]
